In [1]:
# Import library
import pandas as pd

In [2]:
# Reading dataset
data = pd.read_csv('https://raw.githubusercontent.com/analyticsindiamagazine/MocksDatasets/main/Customer_Encoding.csv')
data.head()

S.No.  Cust_ID        City Income Group  Age  Purchase
0      1   560028   Bangalore       Medium   33     90124
1      2   560051   Bangalore       Medium   42     92162
2      3   560050        Pune       Medium   54    137630
3      4   560064  Hyederabad         High   56     53135
4      5   560064   Bangalore       Medium   22    128103

#**Label Encoding**

In [3]:
# Counting category labels
data['Income Group'].value_counts()

Medium    7
High      2
Low       1
Name: Income Group, dtype: int64

In [4]:
# Library for ordinal / label encoding
from sklearn.preprocessing import OrdinalEncoder

In [5]:
# Ordinal / label encoding
ord_enc = OrdinalEncoder()
data["Income Group"] = ord_enc.fit_transform(data[["Income Group"]])
data

S.No.  Cust_ID        City  Income Group  Age  Purchase
0      1   560028   Bangalore           2.0   33     90124
1      2   560051   Bangalore           2.0   42     92162
2      3   560050        Pune           2.0   54    137630
3      4   560064  Hyederabad           0.0   56     53135
4      5   560064   Bangalore           2.0   22    128103
5      6   560076   Bangalore           1.0   27     93574
6      7   560016       Delhi           0.0   45    112004
7      8   560033     Chennai           2.0   38     53316
8      9   560037        Pune           2.0   41    101246
9     10   560056   Bangalore           2.0   39     87154

In [6]:
data = pd.read_csv('https://raw.githubusercontent.com/analyticsindiamagazine/MocksDatasets/main/Customer_Encoding.csv')
data

S.No.  Cust_ID        City Income Group  Age  Purchase
0      1   560028   Bangalore       Medium   33     90124
1      2   560051   Bangalore       Medium   42     92162
2      3   560050        Pune       Medium   54    137630
3      4   560064  Hyederabad         High   56     53135
4      5   560064   Bangalore       Medium   22    128103
5      6   560076   Bangalore          Low   27     93574
6      7   560016       Delhi         High   45    112004
7      8   560033     Chennai       Medium   38     53316
8      9   560037        Pune       Medium   41    101246
9     10   560056   Bangalore       Medium   39     87154

In [7]:
# Normal labelling
data['Income Group'] = data['Income Group'].replace(to_replace=['Low','Medium', 'High'], value=[1, 2, 3])
data

S.No.  Cust_ID        City  Income Group  Age  Purchase
0      1   560028   Bangalore             2   33     90124
1      2   560051   Bangalore             2   42     92162
2      3   560050        Pune             2   54    137630
3      4   560064  Hyederabad             3   56     53135
4      5   560064   Bangalore             2   22    128103
5      6   560076   Bangalore             1   27     93574
6      7   560016       Delhi             3   45    112004
7      8   560033     Chennai             2   38     53316
8      9   560037        Pune             2   41    101246
9     10   560056   Bangalore             2   39     87154

#**One-Hot Encoding**

In [8]:
data['City'].value_counts()

Bangalore     5
Pune          2
Hyederabad    1
Delhi         1
Chennai       1
Name: City, dtype: int64

In [9]:
pd.get_dummies(data, columns = ['City'], prefix = ['City'])  #without using sklearn

S.No.  Cust_ID  Income Group  Age  Purchase  City_Bangalore  City_Chennai  \
0      1   560028             2   33     90124               1             0   
1      2   560051             2   42     92162               1             0   
2      3   560050             2   54    137630               0             0   
3      4   560064             3   56     53135               0             0   
4      5   560064             2   22    128103               1             0   
5      6   560076             1   27     93574               1             0   
6      7   560016             3   45    112004               0             0   
7      8   560033             2   38     53316               0             1   
8      9   560037             2   41    101246               0             0   
9     10   560056             2   39     87154               1             0   

   City_Delhi  City_Hyederabad  City_Pune  
0           0                0          0  
1           0                0          0  
2           0                0          1  
3           0                1          0  
4           0                0          0  
5           0                0          0  
6           1                0          0  
7           0                0          0  
8           0                0          1  
9           0                0          0

In [10]:
data = pd.read_csv('https://raw.githubusercontent.com/analyticsindiamagazine/MocksDatasets/main/Customer_Encoding.csv')
data

S.No.  Cust_ID        City Income Group  Age  Purchase
0      1   560028   Bangalore       Medium   33     90124
1      2   560051   Bangalore       Medium   42     92162
2      3   560050        Pune       Medium   54    137630
3      4   560064  Hyederabad         High   56     53135
4      5   560064   Bangalore       Medium   22    128103
5      6   560076   Bangalore          Low   27     93574
6      7   560016       Delhi         High   45    112004
7      8   560033     Chennai       Medium   38     53316
8      9   560037        Pune       Medium   41    101246
9     10   560056   Bangalore       Medium   39     87154

In [11]:
data["Income Group"] = ord_enc.fit_transform(data[["Income Group"]])
data

S.No.  Cust_ID        City  Income Group  Age  Purchase
0      1   560028   Bangalore           2.0   33     90124
1      2   560051   Bangalore           2.0   42     92162
2      3   560050        Pune           2.0   54    137630
3      4   560064  Hyederabad           0.0   56     53135
4      5   560064   Bangalore           2.0   22    128103
5      6   560076   Bangalore           1.0   27     93574
6      7   560016       Delhi           0.0   45    112004
7      8   560033     Chennai           2.0   38     53316
8      9   560037        Pune           2.0   41    101246
9     10   560056   Bangalore           2.0   39     87154

In [12]:
data2 = data.drop(['Purchase'], axis=1)
data2

S.No.  Cust_ID        City  Income Group  Age
0      1   560028   Bangalore           2.0   33
1      2   560051   Bangalore           2.0   42
2      3   560050        Pune           2.0   54
3      4   560064  Hyederabad           0.0   56
4      5   560064   Bangalore           2.0   22
5      6   560076   Bangalore           1.0   27
6      7   560016       Delhi           0.0   45
7      8   560033     Chennai           2.0   38
8      9   560037        Pune           2.0   41
9     10   560056   Bangalore           2.0   39

In [13]:
X = data2.iloc[:,2:]
X

City  Income Group  Age
0   Bangalore           2.0   33
1   Bangalore           2.0   42
2        Pune           2.0   54
3  Hyederabad           0.0   56
4   Bangalore           2.0   22
5   Bangalore           1.0   27
6       Delhi           0.0   45
7     Chennai           2.0   38
8        Pune           2.0   41
9   Bangalore           2.0   39

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[ 1.  0.  0.  0.  0.  2. 33.]
 [ 1.  0.  0.  0.  0.  2. 42.]
 [ 0.  0.  0.  0.  1.  2. 54.]
 [ 0.  0.  0.  1.  0.  0. 56.]
 [ 1.  0.  0.  0.  0.  2. 22.]
 [ 1.  0.  0.  0.  0.  1. 27.]
 [ 0.  0.  1.  0.  0.  0. 45.]
 [ 0.  1.  0.  0.  0.  2. 38.]
 [ 0.  0.  0.  0.  1.  2. 41.]
 [ 1.  0.  0.  0.  0.  2. 39.]]


#**Binary Encoding**

In [16]:
# Installing library
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 69 kB 3.9 MB/s 


In [17]:
# Importing library
import category_encoders as ce

In [18]:
data = pd.read_csv('https://raw.githubusercontent.com/analyticsindiamagazine/MocksDatasets/main/Customer_Encoding.csv')
data

S.No.  Cust_ID        City Income Group  Age  Purchase
0      1   560028   Bangalore       Medium   33     90124
1      2   560051   Bangalore       Medium   42     92162
2      3   560050        Pune       Medium   54    137630
3      4   560064  Hyederabad         High   56     53135
4      5   560064   Bangalore       Medium   22    128103
5      6   560076   Bangalore          Low   27     93574
6      7   560016       Delhi         High   45    112004
7      8   560033     Chennai       Medium   38     53316
8      9   560037        Pune       Medium   41    101246
9     10   560056   Bangalore       Medium   39     87154

In [19]:
# Binary encoding
encoder= ce.BinaryEncoder(cols=['City'],return_df=True)
data=encoder.fit_transform(data) 
data

S.No.  Cust_ID  City_0  City_1  City_2 Income Group  Age  Purchase
0      1   560028       0       0       1       Medium   33     90124
1      2   560051       0       0       1       Medium   42     92162
2      3   560050       0       1       0       Medium   54    137630
3      4   560064       0       1       1         High   56     53135
4      5   560064       0       0       1       Medium   22    128103
5      6   560076       0       0       1          Low   27     93574
6      7   560016       1       0       0         High   45    112004
7      8   560033       1       0       1       Medium   38     53316
8      9   560037       0       1       0       Medium   41    101246
9     10   560056       0       0       1       Medium   39     87154

#**Hash Encoding**

In [20]:
data = pd.read_csv('https://raw.githubusercontent.com/analyticsindiamagazine/MocksDatasets/main/Customer_Encoding.csv')
data

S.No.  Cust_ID        City Income Group  Age  Purchase
0      1   560028   Bangalore       Medium   33     90124
1      2   560051   Bangalore       Medium   42     92162
2      3   560050        Pune       Medium   54    137630
3      4   560064  Hyederabad         High   56     53135
4      5   560064   Bangalore       Medium   22    128103
5      6   560076   Bangalore          Low   27     93574
6      7   560016       Delhi         High   45    112004
7      8   560033     Chennai       Medium   38     53316
8      9   560037        Pune       Medium   41    101246
9     10   560056   Bangalore       Medium   39     87154

In [21]:
# Hash encoding
encoder=ce.HashingEncoder(cols='City', n_components=4)
data = encoder.fit_transform(data)
data

col_0  col_1  col_2  col_3  S.No.  Cust_ID Income Group  Age  Purchase
0      1      0      0      0      1   560028       Medium   33     90124
1      1      0      0      0      2   560051       Medium   42     92162
2      1      0      0      0      3   560050       Medium   54    137630
3      0      0      1      0      4   560064         High   56     53135
4      1      0      0      0      5   560064       Medium   22    128103
5      1      0      0      0      6   560076          Low   27     93574
6      0      0      1      0      7   560016         High   45    112004
7      0      0      1      0      8   560033       Medium   38     53316
8      1      0      0      0      9   560037       Medium   41    101246
9      1      0      0      0     10   560056       Medium   39     87154